name: Docker Image CI

on:
    push:
        branches: ["release-*"]
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    build-and-push-www:
        name: Build and push "www" image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: jkulak/smartplaylist-www
                  tags: |
                      type=ref,event=branch
                      type=ref,event=tag
                      type=raw,value=latest

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push "www"
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
    deploy-www:
        name: Redeploy "www"
        runs-on: ubuntu-latest
        needs: [build-and-push-www]
        steps:
            - name: Deploy docker container webhook
              uses: joelwmale/webhook-action@master
              with:
                  url: ${{ secrets.DEPLOY_WEBHOOK_URL }}/deploy-www
                  headers: '{"secret": "${{ secrets.WEBHOOK_SECRET }}"}'
